function(createVersionH target)
get_target_property(version ${target} VERSION)
get_target_property(dir ${target} CMAKE_SOURCE_DIR)
#[[string(TOUPPER ${target} target_upper)

file(WRITE "${CMAKE_SOURCE_DIR}/build_scripts/${target}VersionH.cmake" "
string(TIMESTAMP date \"%d-%m-%Y:%H:%S\")
string(TIMESTAMP date_extra \"%A %b %y\")
set(versionHContent \"// This is auto generated by cmake
#ifndef ${target_upper}_VERSION_H
#define ${target_upper}_VERSION_H

#define ${target_upper}_VERSION_STRING \\\"${version}\\\"
#define ${target_upper}_BUILD_DATE \\\"\${date}\\\"
#define ${target_upper}_BUILD_DATE_EXTRA \\\"\${date_extra}\\\"

#endif\")

file(WRITE \"${dir}/version.h\" \"\${versionHContent}\")
")]]

add_custom_command(TARGET ${target} PRE_BUILD
  COMMAND python
  ${CMAKE_SOURCE_DIR}/build_scripts/versionh.py
  ${target}
  ${version}
  "${dir}/${target}_version.h")
endfunction()